runtime: python311
entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /uploads
  static_dir: uploads  # Serve files from the "uploads" folder as static content

- url: /templates
  static_dir: templates  # Serve files from the "templates" folder as static content
  